[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"
#runner = "elf2uf2-rs -d"
rustflags = [
    "-C", "link-arg=-Tlink.ld",
]


[build]
target = "thumbv6m-none-eabi"